version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9-browsers
    working_directory: ~/repos
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "NPM Test"
          command: npm run test:ci
      - run:
          name: "NPM Build"
          command: npm run build:prod
      - run:
          name: "Firebase Deploy"
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
